package common;

public enum PageType {
	//ADMIN NAME PAGE
	USER_MANAGEMENT_PAGE, REPORT_MANAGEMENT_PAGE, VIDEO_MANAGEMENT_PAGE,
	
	//USER NAME PAGE
	SITE_HOME_PAGE, SITE_USER_PROFILE, SITE_USER_FAVORITE, SITE_MOVIE_SINGLE,
	SITE_FORGOT_PASSWORD, SITE_SHARE_PAGE
}
